language: python
python:
  - "2.7"
  - "3.5"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.pip-cache/
    - $HOME/virtualenv/python2.7/lib/python2.7/site-packages

env:
  matrix:
  - TEST_SUITE=unittest CMAKE_BUILD_TYPE=Release PRJ_COMPILER=clang
  - TEST_SUITE=unittest CMAKE_BUILD_TYPE=Debug PRJ_COMPILER=clang
  - TEST_SUITE=unittest CMAKE_BUILD_TYPE=Release PRJ_COMPILER=gcc
  - TEST_SUITE=unittest CMAKE_BUILD_TYPE=Debug PRJ_COMPILER=gcc
  - TEST_SUITE=benchmark

addons:
  apt:
    packages:
      - python-dev
      - python-numpy
      - valgrind
      - cppcheck
      - memcached
      - libmemcached6
      - golang

install:
  - pip install --upgrade pip
  - pip install future
  - pip install --upgrade setuptools
  - if [ $TEST_SUITE = "unittest" ]; then pip install pytest greenify gevent; fi
  - if [ $TEST_SUITE = "benchmark" ]; then pip install python-memcached pylibmc; fi

before_script:
  - ./misc/memcached_server start

script:
  - if [ $PRJ_COMPILER = "gcc" ]; then export CC=gcc CXX=g++; fi
  - if [ $PRJ_COMPILER = "clang" ]; then export CC=clang CXX=clang++; fi
  - ./misc/travis/$TEST_SUITE.sh

after_script:
  - ./misc/memcached_server stop
